### ISSUE TITLE
Connect database with website

### ISSUE THREAD

**Issue by Cordobro** [Mehdows/D0018E#13]
Sprint 2

connect the website to the database

**Comment by TovahParnes** [comment]
Can connect to mysql using localhost but not otherwise. Probably some error with access or ports.

**Comment by TovahParnes** [comment]
We can connect, but only on the schools network. Use the user ConnectUser to connect

**Comment by TovahParnes** [comment]
https://askubuntu.com/questions/337874/change-apache-document-root-folder-to-secondary-hard-drive
