### ISSUE TITLE
Display the accurate information on the home page

### ISSUE THREAD

**Issue by Cordobro** [Mehdows/D0018E#37]
Just fix the function

**Comment by Cordobro** [comment]
https://codeconvey.com/comment-box-in-html-and-css/

For the comment design

**Comment by TovahParnes** [comment]
displaying items: https://www.w3schools.com/php/php_mysql_select.asp

**Comment by TovahParnes** [comment]
button css: https://stackoverflow.com/questions/710089/how-do-i-make-an-html-link-look-like-a-button

**Comment by TovahParnes** [comment]
the items are displayed via a while loop, making a new row after three elements. there is still no function for clicking on the buy button or any connection to which item the button corresponds to.
